translations:
  - 'en-US'
check:
  redstoneAndRepeater: true
  observer: true
  piston: true
  comparator: true
  sculk: true
  ignoredWorlds:
    - world
  ignoredRegions: []

clock:
  endDelay: 300
  maxCount: 150
  autoBreak: true
  notifyAdmins: false
  notifyConsole: true
  drop: true

tps:
  interval: 2
  max: 20
  min: 15