translations:
  - 'en-US'
check:
  redstoneAndRepeater: true
  observer: true
  piston: true
  comparator: true
  sculk: true
  ignoredWorlds:
    - world
  ignoredRegions: []

clock:
  endDelay: 300
  maxCount: 150
  autoBreak: true
  notifyAdmins: false
  notifyConsole: true
  drop: true

tps:
  interval: 2
  max: 20
  min: 15

notification:
  # Should be lowercase
  enabled:
    - console
    - admins
    - discord
    - sign
  discord:
    webhook: "_here_comes_the_webhook_url_"
    avatar: "https://cdn.modrinth.com/data/UWh9tyEa/ea7b1aded47652100a1f0e8673e87c124b38fc08_96.webp"
    # Should be a hex color code without the #
    color: 0xFF00FF
    description: |
      <red><bold>There is a redstone clock in <world> at <x>,<y>,<z></bold>
    fields:
      - name: "Teleport Command"
        value: "/teleport <x> <y> <z>"
        inline: true
      

  sign:
    material: OAK_SIGN
    # Should be a list of strings for each line of the sign
    # The max length of each line is 16 characters
    front:
      - "<red>RedstoneClocks!"
      - "<red>Are"
      - "<red>prohibited"
    back:
      - "<red>RedstoneClocks!"
      - "<red>Are"
      - "<red>prohibited"
