name: Behavior Bug or Plugin Incompatibility
description: Report issues with plugin incompatibility or other behavior related issues.
labels: [ "status: needs triage", "type: bug" ]
projects: ["OneLiteFeatherNET/6"]
assignees: ["OneLiteFeatherNET/antiredstoneclock-remastered-triage"]
body:
  - type: textarea
    id: server-logs
    attributes:
      label: Server Logs
      description: |
        Upload your server log from `logs/latest.log` here
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: What you actually saw.
    validations:
      required: true

  - type: textarea
    config: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true

  - type: textarea
    id: plugin-and-datapack-list
    attributes:
      label: Plugin and Datapack List
      description: |
        All plugins and datapacks running on your server.
        To list plugins, run `/plugins`. For datapacks, run `/datapack list`.
    validations:
      required: true

  - type: textarea
    id: paper-version
    attributes:
      label: Paper version
      description: |
        Run `/version` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > version
        [19:36:32 INFO]: Checking version, please wait...
        [19:36:32 INFO]: This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
        You are running the latest version
        Previous version: git-Paper-446 (MC: 1.19.3)
        ```

        </details>
    validations:
      required: true
  - type: textarea
    id: plugin-version
    attributes:
      label: Plugin version
      description: |
        Run `/about AntiRedstoneClock-Remastered` on your server and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/about AntiRedstoneClock-Remastered` so we can adequately track down the issue.
        Additionally, do NOT provide a screenshot, you MUST paste the entire output.
        <details>
        <summary>Example</summary>

        ```
        > about AntiRedstoneClock-Remastered
        [19:37:16 INFO]: AntiRedstoneClock-Remastered version 1.1.0
        [19:37:16 INFO]: Authors: OneLiteFeather and TheMeinerLP
        ```

        </details>
    validations:
      required: true
  - type: textarea
    id: other-information
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false

  - type: markdown
    id: pre-submission-checklist
    attributes:
      value: |
        Before submitting this issue, please ensure the following:

        1. You are running the latest version of Paper from [our downloads page](https://papermc.io/downloads).
        2. You searched for and ensured there isn't already an open issue regarding this.
        3. Your version of Minecraft is supported by AntiRedstoneClock-Remastered.
        4. You are running the latest version of AntiRedstoneClock-Remastered from [our hangar page](https://hangar.papermc.io/OneLiteFeather/AntiRedstoneClock-Remastered).