name: Build AntiRedstoneClock-Remastered
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    # Run on all label events (won't be duplicated) or all push events or on PR syncs not from the same repo
    if: github.repository_owner == 'OneLiteFeatherNET'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          cache: gradle
          java-version: 17
      - name: Clean Build
        run: ./gradlew clean build shadowJar --no-daemon
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AntiRedstoneClock-Remastered Archive
          path: build/libs/AntiRedstoneClock-Remastered-*.jar
      - name: Publish to hangar
        if: ${{ runner.os == 'Linux'}}
        run: ./gradlew publishAllPublicationsToHangar --no-daemon
        env:
          HANGAR_SECRET: ${{secrets.HANGAR_KEY}}
      - name: Publish to Modrinth
        if: ${{ runner.os == 'Linux' }}
        run: ./gradlew modrinth  --no-daemon
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_KEY }}