name: Publish
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    # Run on all label events (won't be duplicated) or all push events or on PR syncs not from the same repo
    if: github.repository_owner == 'OneLiteFeatherNET'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          cache: gradle
          java-version: 17
      - name: Publish
        env:
          HANGAR_SECRET: ${{secrets.HANGAR_KEY}}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_KEY }}
          ELDO_USERNAME: "${{ secrets.ELDO_USERNAME }}"
          ELDO_PASSWORD: "${{ secrets.ELDO_PASSWORD }}"
        run: ./gradlew build modrinth publishAllPublicationsToHangar publish
